set(TUHHSDK_SOURCES
  ${TUHHSDK_HOME}/Data/MirrorableMotionOutput.cpp
  ${TUHHSDK_HOME}/Definitions/BHULKsStandardMessage.cpp
  ${TUHHSDK_HOME}/Definitions/keys.cpp
  ${TUHHSDK_HOME}/Framework/Database.cpp
  ${TUHHSDK_HOME}/Framework/DebugDatabase.cpp
  ${TUHHSDK_HOME}/Framework/Messaging.cpp
  ${TUHHSDK_HOME}/Framework/Module.cpp
  ${TUHHSDK_HOME}/Framework/ModuleManagerInterface.cpp
  ${TUHHSDK_HOME}/Framework/Thread.cpp
  ${TUHHSDK_HOME}/Libs/jsoncpp.cpp
  ${TUHHSDK_HOME}/Modules/Configuration/Configuration.cpp
  ${TUHHSDK_HOME}/Modules/Configuration/NetworkConfig.cpp
  ${TUHHSDK_HOME}/Modules/Configuration/UnixSocketConfig.cpp
  ${TUHHSDK_HOME}/Modules/Debug/Debug.cpp
  ${TUHHSDK_HOME}/Modules/Debug/FileTransport.cpp
  ${TUHHSDK_HOME}/Modules/Debug/JpegConverter.cpp
  ${TUHHSDK_HOME}/Modules/Debug/PngConverter.cpp
  ${TUHHSDK_HOME}/Modules/Debug/StreamCompression.cpp
  ${TUHHSDK_HOME}/Modules/Debug/TCPTransport.cpp
  ${TUHHSDK_HOME}/Modules/Debug/UnixSocketTransport.cpp
  #${TUHHSDK_HOME}/Modules/MachineLearning/NeuralNetwork/NeuralNetwork.cpp
  ${TUHHSDK_HOME}/Modules/NaoProvider.cpp
  ${TUHHSDK_HOME}/Modules/Network/AlivenessTransmitter.cpp
  ${TUHHSDK_HOME}/Modules/Poses.cpp
  ${TUHHSDK_HOME}/print.cpp
  ${TUHHSDK_HOME}/SharedObject.cpp
  ${TUHHSDK_HOME}/SharedObjectManager.cpp
  ${TUHHSDK_HOME}/Tools/Chronometer.cpp
  ${TUHHSDK_HOME}/Tools/Kinematics/Com.cpp
  ${TUHHSDK_HOME}/Tools/Kinematics/ForwardKinematics.cpp
  ${TUHHSDK_HOME}/Tools/Kinematics/InverseKinematics.cpp
  ${TUHHSDK_HOME}/Tools/Math/ColorConverter.cpp
  ${TUHHSDK_HOME}/Tools/Math/Correlation.cpp
  ${TUHHSDK_HOME}/Tools/Math/FFT.cpp
  ${TUHHSDK_HOME}/Tools/Math/HungarianMethod.cpp
#  ${TUHHSDK_HOME}/Tools/Math/KalmanFilter.cpp
  ${TUHHSDK_HOME}/Tools/Math/Random.cpp
  ${TUHHSDK_HOME}/Tools/StateEstimation/Covariance.hpp
  ${TUHHSDK_HOME}/Tools/StateEstimation/ProjectionMeasurementModel.hpp
  ${TUHHSDK_HOME}/Tools/StateMachine/Option.hpp
  ${TUHHSDK_HOME}/Tools/Storage/Image.cpp
  ${TUHHSDK_HOME}/Tools/Storage/Image422.cpp
  ${TUHHSDK_HOME}/Tools/Storage/XPMImage.cpp
  ${TUHHSDK_HOME}/Tools/Storage/UniValue/UniValue.cpp
  ${TUHHSDK_HOME}/Tools/Storage/UniValue/UniValue2JsonString.cpp
  ${TUHHSDK_HOME}/Tools/Time.cpp
  ${TUHHSDK_HOME}/tuhh.cpp
)

set(TUHHSDK_HEADERS
  ${TUHHSDK_HOME}/Data/AudioData.hpp
  ${TUHHSDK_HOME}/Data/BallData.hpp
  ${TUHHSDK_HOME}/Data/BallSearchMap.hpp
  ${TUHHSDK_HOME}/Data/BallState.hpp
  ${TUHHSDK_HOME}/Data/BatteryData.hpp
  ${TUHHSDK_HOME}/Data/BishopPosition.hpp
  #${TUHHSDK_HOME}/Data/BodyLeaningOutput.hpp
  ${TUHHSDK_HOME}/Data/BodyPose.hpp
  ${TUHHSDK_HOME}/Data/BodyRotationData.hpp
  ${TUHHSDK_HOME}/Data/BallSearchPosition.hpp
  ${TUHHSDK_HOME}/Data/ButtonData.hpp
  ${TUHHSDK_HOME}/Data/CameraMatrix.hpp
  ${TUHHSDK_HOME}/Data/CircleData.hpp
  ${TUHHSDK_HOME}/Data/CycleInfo.hpp
  ${TUHHSDK_HOME}/Data/DefendingPosition.hpp
  ${TUHHSDK_HOME}/Data/EyeLEDRequest.hpp
  ${TUHHSDK_HOME}/Data/FallManagerOutput.hpp
  ${TUHHSDK_HOME}/Data/FieldBorder.hpp
  ${TUHHSDK_HOME}/Data/FieldColor.hpp
  ${TUHHSDK_HOME}/Data/FieldDimensions.hpp
  ${TUHHSDK_HOME}/Data/FilteredSegments.hpp
  ${TUHHSDK_HOME}/Data/FSRSensorData.hpp
  ${TUHHSDK_HOME}/Data/GameControllerState.hpp
  ${TUHHSDK_HOME}/Data/GoalData.hpp
  ${TUHHSDK_HOME}/Data/HeadPositionData.hpp
  ${TUHHSDK_HOME}/Data/HeadMatrixBuffer.hpp
  ${TUHHSDK_HOME}/Data/HeadMotionOutput.hpp
  ${TUHHSDK_HOME}/Data/FakeImageData.hpp
  ${TUHHSDK_HOME}/Data/ImageData.hpp
  ${TUHHSDK_HOME}/Data/ImageSegments.hpp
  ${TUHHSDK_HOME}/Data/IMUSensorData.hpp
  ${TUHHSDK_HOME}/Data/JointCalibrationData.hpp
  ${TUHHSDK_HOME}/Data/JointSensorData.hpp
  ${TUHHSDK_HOME}/Data/KeeperAction.hpp
  ${TUHHSDK_HOME}/Data/KeeperOutput.hpp
  ${TUHHSDK_HOME}/Data/KickOutput.hpp
  ${TUHHSDK_HOME}/Data/LandmarkModel.hpp
  ${TUHHSDK_HOME}/Data/LineData.hpp
  ${TUHHSDK_HOME}/Data/MirrorableMotionOutput.hpp
  ${TUHHSDK_HOME}/Data/MotionActivation.hpp
  ${TUHHSDK_HOME}/Data/MotionOutput.hpp
  ${TUHHSDK_HOME}/Data/MotionPlannerOutput.hpp
  ${TUHHSDK_HOME}/Data/MotionRequest.hpp
  ${TUHHSDK_HOME}/Data/MotionState.hpp
  ${TUHHSDK_HOME}/Data/NTPData.hpp
  ${TUHHSDK_HOME}/Data/NoWifiData.hpp
  ${TUHHSDK_HOME}/Data/ObstacleData.hpp
  ${TUHHSDK_HOME}/Data/OdometryData.hpp
  ${TUHHSDK_HOME}/Data/OdometryOffset.hpp
  ${TUHHSDK_HOME}/Data/Path.hpp
  ${TUHHSDK_HOME}/Data/PenaltySpotData.hpp
  ${TUHHSDK_HOME}/Data/PenaltyKeeperAction.hpp
  ${TUHHSDK_HOME}/Data/PlayerConfiguration.hpp
  ${TUHHSDK_HOME}/Data/PlayingRoles.hpp
  ${TUHHSDK_HOME}/Data/PointOutput.hpp
  ${TUHHSDK_HOME}/Data/RawTeamPlayers.hpp
  ${TUHHSDK_HOME}/Data/ReplayData.hpp
  ${TUHHSDK_HOME}/Data/PoserOutput.hpp
  ${TUHHSDK_HOME}/Data/RobotData.hpp
  ${TUHHSDK_HOME}/Data/RobotKinematics.hpp
  ${TUHHSDK_HOME}/Data/RobotPosition.hpp
  ${TUHHSDK_HOME}/Data/RobotProjection.hpp
  ${TUHHSDK_HOME}/Data/SPLNetworkData.hpp
  ${TUHHSDK_HOME}/Data/SetPosition.hpp
  ${TUHHSDK_HOME}/Data/SlidingWindows.hpp
  ${TUHHSDK_HOME}/Data/SonarData.hpp
  ${TUHHSDK_HOME}/Data/StandUpOutput.hpp
  ${TUHHSDK_HOME}/Data/StandUpResult.hpp
  ${TUHHSDK_HOME}/Data/StrikerAction.hpp
  ${TUHHSDK_HOME}/Data/SupportingPosition.hpp
  ${TUHHSDK_HOME}/Data/TeamBallModel.hpp
  ${TUHHSDK_HOME}/Data/TeamObstacleData.hpp
  ${TUHHSDK_HOME}/Data/TeamPlayers.hpp
  ${TUHHSDK_HOME}/Data/TimeToReachBall.hpp
  ${TUHHSDK_HOME}/Data/WalkGenerator.hpp
  ${TUHHSDK_HOME}/Data/WalkingEngineWalkOutput.hpp
  ${TUHHSDK_HOME}/Data/WalkingEngineStandOutput.hpp
  ${TUHHSDK_HOME}/Data/WhistleData.hpp
  ${TUHHSDK_HOME}/Data/WorldState.hpp
  #${TUHHSDK_HOME}/Definitions/BHULKsStandardMessage.h
  #${TUHHSDK_HOME}/Definitions/keys.h
  #${TUHHSDK_HOME}/Definitions/RoboCupGameControlData.h
  #${TUHHSDK_HOME}/Definitions/SPLStandardMessage.h
  #${TUHHSDK_HOME}/Definitions/SPLNoWifiChallenge.h
  #${TUHHSDK_HOME}/Definitions/SPLCoachMessage.h
  #${TUHHSDK_HOME}/Definitions/windows_definition_fix.hpp
  #${TUHHSDK_HOME}/Definitions/XPMImages.h
  #${TUHHSDK_HOME}/Framework/Database.hpp
  #${TUHHSDK_HOME}/Framework/DataType.hpp
  #${TUHHSDK_HOME}/Framework/DebugDatabase.hpp
  #${TUHHSDK_HOME}/Framework/Messaging.hpp
  #${TUHHSDK_HOME}/Framework/Module.hpp
  #${TUHHSDK_HOME}/Framework/ModuleManagerInterface.hpp
  #${TUHHSDK_HOME}/Framework/Thread.hpp
  #${TUHHSDK_HOME}/Hardware/AudioInterface.hpp
  #${TUHHSDK_HOME}/Hardware/FakeDataInterface.hpp
  ${TUHHSDK_HOME}/Hardware/CameraInterface.hpp
  #${TUHHSDK_HOME}/Hardware/RobotInterface.hpp
  #${TUHHSDK_HOME}/Libs/json/json-forwards.h
  #${TUHHSDK_HOME}/Libs/json/json.h
  ${TUHHSDK_HOME}/Modules/Configuration/ConfigMessageHeader.h
  ${TUHHSDK_HOME}/Modules/Configuration/Configuration.h
  ${TUHHSDK_HOME}/Modules/Configuration/NetworkConfig.hpp
  ${TUHHSDK_HOME}/Modules/Configuration/UnixSocketConfig.hpp
  ${TUHHSDK_HOME}/Modules/Debug/Debug.h
  ${TUHHSDK_HOME}/Modules/Debug/DebugData.h
  ${TUHHSDK_HOME}/Modules/Debug/DebugMessageFormat.h
  ${TUHHSDK_HOME}/Modules/Debug/DebugTransportInterface.h
  ${TUHHSDK_HOME}/Modules/Debug/FileTransport.h
  ${TUHHSDK_HOME}/Modules/Debug/ImageConverterInterface.h
  ${TUHHSDK_HOME}/Modules/Debug/JpegConverter.h
  ${TUHHSDK_HOME}/Modules/Debug/PngConverter.h
  ${TUHHSDK_HOME}/Modules/Debug/StreamCompression.h
  ${TUHHSDK_HOME}/Modules/Debug/Subscription.h
  ${TUHHSDK_HOME}/Modules/Debug/TCPTransport.h
  ${TUHHSDK_HOME}/Modules/Debug/UnixSocketTransport.hpp
  ${TUHHSDK_HOME}/Modules/Log/Log.h
  #${TUHHSDK_HOME}/Modules/MachineLearning/NeuralNetwork/NeuralNetwork.hpp
  ${TUHHSDK_HOME}/Modules/NaoProvider.h
  ${TUHHSDK_HOME}/Modules/Network/AlivenessMessage.h
  ${TUHHSDK_HOME}/Modules/Network/AlivenessTransmitter.h
  ${TUHHSDK_HOME}/Modules/Poses.h
  #${TUHHSDK_HOME}/print.h
  #${TUHHSDK_HOME}/SharedObject.hpp
  #${TUHHSDK_HOME}/SharedObjectManager.hpp
  ${TUHHSDK_HOME}/Tools/BallUtils.hpp
  ${TUHHSDK_HOME}/Tools/Chronometer.hpp
  ${TUHHSDK_HOME}/Tools/Kinematics/Com.h
  ${TUHHSDK_HOME}/Tools/Kinematics/ForwardKinematics.h
  ${TUHHSDK_HOME}/Tools/Kinematics/InverseKinematics.h
  ${TUHHSDK_HOME}/Tools/Kinematics/KinematicMatrix.h
  ${TUHHSDK_HOME}/Tools/Math/Angle.hpp
  ${TUHHSDK_HOME}/Tools/Math/Arc.hpp
  ${TUHHSDK_HOME}/Tools/Math/Circle.hpp
  ${TUHHSDK_HOME}/Tools/Math/ColorConverter.hpp
  ${TUHHSDK_HOME}/Tools/Math/Correlation.hpp
  ${TUHHSDK_HOME}/Tools/Math/Eigen.hpp
  ${TUHHSDK_HOME}/Tools/Math/FFT.hpp
  ${TUHHSDK_HOME}/Tools/Math/Geometry.hpp
  ${TUHHSDK_HOME}/Tools/Math/HungarianMethod.hpp
  ${TUHHSDK_HOME}/Tools/Math/Hysteresis.hpp
#  ${TUHHSDK_HOME}/Tools/Math/KalmanFilter.h
  ${TUHHSDK_HOME}/Tools/Math/Line.hpp
  ${TUHHSDK_HOME}/Tools/Math/Pose.hpp
  ${TUHHSDK_HOME}/Tools/Math/Range.hpp
  ${TUHHSDK_HOME}/Tools/Math/Random.hpp
  ${TUHHSDK_HOME}/Tools/Math/Statistics.hpp
  ${TUHHSDK_HOME}/Tools/Math/Velocity.hpp
  ${TUHHSDK_HOME}/Tools/Storage/Image.hpp
  ${TUHHSDK_HOME}/Tools/Storage/Image422.hpp
  ${TUHHSDK_HOME}/Tools/Storage/UniValue/UniConvertible.hpp
  ${TUHHSDK_HOME}/Tools/Storage/UniValue/UniValue.h
  ${TUHHSDK_HOME}/Tools/Storage/UniValue/UniValue2Json.hpp
  ${TUHHSDK_HOME}/Tools/Storage/UniValue/UniValue2JsonString.h
  ${TUHHSDK_HOME}/Tools/Storage/UniValue/EigenStreaming.hpp
  ${TUHHSDK_HOME}/Tools/Storage/XPMImage.hpp
  ${TUHHSDK_HOME}/Tools/Time.hpp
  ${TUHHSDK_HOME}/Tools/Var/SpscQueue.hpp
  #${TUHHSDK_HOME}/tuhh.hpp
)
