#include "Sensors.hpp"

const std::vector<JOINTS::JOINT> Sensor::CAM_OBS_L_SUP_FOOT = {
    JOINTS::JOINT::HEAD_YAW,        JOINTS::JOINT::HEAD_PITCH,
    JOINTS::JOINT::L_HIP_YAW_PITCH, JOINTS::JOINT::L_HIP_ROLL,
    JOINTS::JOINT::L_HIP_PITCH,     JOINTS::JOINT::L_KNEE_PITCH,
    JOINTS::JOINT::L_ANKLE_PITCH,   JOINTS::JOINT::L_ANKLE_ROLL};

const std::vector<JOINTS::JOINT> Sensor::CAM_OBS_R_SUP_FOOT = {
    JOINTS::JOINT::HEAD_YAW,        JOINTS::JOINT::HEAD_PITCH,
    JOINTS::JOINT::R_HIP_YAW_PITCH, JOINTS::JOINT::R_HIP_ROLL,
    JOINTS::JOINT::R_HIP_PITCH,     JOINTS::JOINT::R_KNEE_PITCH,
    JOINTS::JOINT::R_ANKLE_PITCH,   JOINTS::JOINT::R_ANKLE_ROLL};

const std::vector<JOINTS::JOINT> Sensor::ALL_OBS_JOINTS = {
    JOINTS::JOINT::HEAD_YAW,        JOINTS::JOINT::HEAD_PITCH,
    JOINTS::JOINT::L_HIP_YAW_PITCH, JOINTS::JOINT::L_HIP_ROLL,
    JOINTS::JOINT::L_HIP_PITCH,     JOINTS::JOINT::L_KNEE_PITCH,
    JOINTS::JOINT::L_ANKLE_PITCH,   JOINTS::JOINT::L_ANKLE_ROLL,
    JOINTS::JOINT::R_HIP_YAW_PITCH, JOINTS::JOINT::R_HIP_ROLL,
    JOINTS::JOINT::R_HIP_PITCH,     JOINTS::JOINT::R_KNEE_PITCH,
    JOINTS::JOINT::R_ANKLE_PITCH,   JOINTS::JOINT::R_ANKLE_ROLL};

const std::vector<std::string> Sensor::JOINT_NAMES = {
    "HEAD_YAW",        "HEAD_PITCH",   "L_SHOULDER_PITCH",
    "L_SHOULDER_ROLL", "L_ELBOW_YAW",  "L_ELBOW_ROLL",
    "L_WRIST_YAW",     "L_HAND",       "L_HIP_YAW_PITCH",
    "L_HIP_ROLL",      "L_HIP_PITCH",  "L_KNEE_PITCH",
    "L_ANKLE_PITCH",   "L_ANKLE_ROLL", "R_HIP_YAW_PITCH",
    "R_HIP_ROLL",      "R_HIP_PITCH",  "R_KNEE_PITCH",
    "R_ANKLE_PITCH",   "R_ANKLE_ROLL", "R_SHOULDER_PITCH",
    "R_SHOULDER_ROLL", "R_ELBOW_YAW",  "R_ELBOW_ROLL",
    "R_WRIST_YAW",     "R_HAND"};
